FROM node:26 as build
 
WORKDIR /app

COPY  package*.json .

RUN npm install --legacy-peer-deps

COPY . .

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

USER nginx



CMD ["nginx","-g", "daemon off;"]